ide: NED editor: fix "Failed to create the part's controls"
Due to:

org.eclipse.core.runtime.AssertionFailedException: assertion failed: file is not a NED file, or not parsed yet
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:110)
	at org.omnetpp.ned.core.NedTypeResolver.getNedFileElement(NedTypeResolver.java:246)
org.eclipse.core.runtime.AssertionFailedException: assertion failed: file is not a NED file, or not parsed yet
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:110)
	at org.omnetpp.ned.core.NedTypeResolver.getNedFileElement(NedTypeResolver.java:246)
	at org.omnetpp.ned.editor.graph.GraphicalNedEditor.getModel(GraphicalNedEditor.java:608)
	at org.omnetpp.ned.editor.graph.GraphicalNedEditor.setInput(GraphicalNedEditor.java:629)
	at org.eclipse.gef.ui.parts.GraphicalEditor.init(GraphicalEditor.java:346)
	at org.omnetpp.ned.editor.graph.GraphicalNedEditor.init(GraphicalNedEditor.java:216)

Note:

   public synchronized NedFileElementEx getNedFileElement(IFile file) {
        Assert.isTrue(nedFiles.containsKey(file), "file is not a NED file, or not parsed yet");
        return nedFiles.get(file);
    }

NedEditorLauncher needs to test the availability of the NED file
in the same way NED editor does: by checking whether the file was
actually loaded (whether resolver.nedFiles contains it)