scave: fix compile error
stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const
resultfilemanager.cc:1356:25:   required from here