python/scave: Workspace: fix error if a renamed project is not directly under the Eclipse workspace directory.
"renamed project" = where name in .project differs from folder name

find_enclosing_project() changes:
- remember project location
- method no longer static (API change)

Traceback:

Error in chart get_parameters: Location found does not look like a project (no `.project` file): /home/andras/projects/omnetpp-src
Traceback (most recent call last):
  File "/home/andras/projects/omnetpp-dev/bin/opp_charttool", line 172, in <module>
    analysis.run_chart(chart, anf_dir, workspace, show=args.show, extra_props=props)
  File "/home/andras/projects/omnetpp-dev/python/omnetpp/scave/analysis.py", line 383, in run_chart
    refprojs = workspace.get_all_referenced_projects(project, True)
  File "/home/andras/projects/omnetpp-dev/python/omnetpp/scave/analysis.py", line 217, in get_all_referenced_projects
    projs = self.get_referenced_projects(project_name)
  File "/home/andras/projects/omnetpp-dev/python/omnetpp/scave/analysis.py", line 207, in get_referenced_projects
    project_file = self.get_project_location(project_name) + "/.project"
  File "/home/andras/projects/omnetpp-dev/python/omnetpp/scave/analysis.py", line 199, in get_project_location
    raise RuntimeError("Location found does not look like a project (no `.project` file): " + location)
RuntimeError: Location found does not look like a project (no `.project` file): /home/andras/projects/omnetpp-src