nedxml/msgc: eliminate the use of operator<< for getFieldValueAsString()
Rationale:

Multiple namespaces caused a problem. Example msg file:

````````````````````
  class C {}

  namespace a;
  class A {}

  namespace h;
  class H {}

  class Foo {
      C c;
      a::A a;
      H h;
  }
````````````````````

C++ compile error: op<< ambiguous in FooDescriptor::getFieldValueAsString(),
because one can be found both via normal and argument-dependent lookup.

FIRST ATTEMPT at fixing was to generate the fallback template rules
only in the toplevel namespace, i.e. call generateTemplates() only once,
in the toplevel namespace. This fixed the above code, but caused weird
C++ compilation error in test/core/msg_namespace_foreignclass_1.test
which tests bringing existing classes into msg (via @existingClass)
that have op<< defined.

C++ code could be simplified to the following issue:

````````````````````
#include <iostream>

// FROM GENERATED CODE (default operator<< for classes that don't have one)
template<typename T>
std::ostream& operator<<(std::ostream& out,const T&) {/*...*/ return out;}

namespace inet {
class Opaque { };

class Unrelated { };
inline std::ostream& operator<<(std::ostream& out, const Unrelated& a) {/*...*/ return out;}  // REMOVING THIS WILL FIX IT

void f() { std::cout << inet::Opaque(); }  // COMPILE ERROR HERE: NO KNOWN CONVERSION

} // namespace inet
````````````````````

No good solution was found.


THEN it was concluded we don't need op<< at all for generating getFieldValueAsString().
We could simply use @toString code if the class has one; or str() if the
class has one; or just do some fallback such as returning empty string
othewise. This is the solution implemented in this commit.