ide/scave: PythonEntryPoint: prevent Java exception traces from appearing in chart message
..and multi-line strings in general (only show the 1st line).
Displaying the whole thing would be too obtrusive, and the full exception
info is printed in the Console anyway.

Example:

"""
py4j.protocol.Py4JJavaError: An error occurred while calling o2.getVectorsPickle.
: py4j.Py4JException: Vector file changed on disk since results were loaded, please reload!
	at org.omnetpp.scave.editors.ResultsProvider.getVectorsPickle(ResultsProvider.java:195)
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:382)
        ...
"""