opp_charttool: fix "Error: 'Namespace' object has no attribute 'verbose'" error in "info" subcommand
The error came from line following line due to info_parser not having a -v option:
utils.set_verbose_export(args.verbose)