sim: cException: getContextModuleID() -> getContextComponentId(), and more
cComponent: added getComponentKind() (and isModule()/isChannel() changed to rely on it)
cException: added getContextComponentKind()