qtenv: simulation->configure() lead to an error, so only read imagepath
error: cannot read "seed-set", as predefined itervars (specifically ${runnumber}) don't exist

reading other settings from global config is not needed, because they'll
be read per run

Signed-off-by: Andras Varga <andras@omnetpp.org>